### ISSUE TITLE
Add search result ordering functions

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/grantnav#10]
It is understood that search results are ordered by "relevance" by default

Add ordering functions to search results - starter list:

- Relevance
- Amount Awarded
- Title 
- Date Awarded

I'd assume that these orders would also need a descending / ascending option too

**Comment by robredpath** [comment]
@stevieflow is advocating for this to go into iteration 7

**Comment by stevieflow** [comment]
+1 for iteration 7 please.  I understand that we might not have plenty of "demand" for this, but the question is often asked "what is determining the order that results are presented in".  Working on this would help people answer this question, by selecting other orderings

**Comment by robredpath** [comment]
@kindly tells me that this isn't too bad to implement

**Comment by robredpath** [comment]
I put @kindly 's proposal of relevance, award date asc/desc and value asc/desc to @stevieflow and Katherine earlier today and they sounded good with it

**Comment by stevieflow** [comment]
+1

On relevance: I assume that you can only sort by relevance in ascending order ?  Or maybe not?
