### ISSUE TITLE
Extra info on region pages has 'Description' prepended

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/grantnav#104]
Looks like the field name gets included in results:

![screen shot 2016-05-06 at 13 04 34](https://cloud.githubusercontent.com/assets/641009/15072512/20fffee6-138b-11e6-9575-ac1cf64b8b14.png)

**Comment by kindly** [comment]
That is intentional for use on smaller screens, when the table width is thinner more fields get added to the expanded section.  So for that case the field names need to be included.  To make this conditional if there is just a "description" seems unnecessary.

**Comment by robredpath** [comment]
How about we stick a colon after the field name? I think that would it clear that it's a field name. I mostly noticed this because the bold isn't particularly heavy.

**Comment by robredpath** [comment]
Just to summarise the conversation I had with @kindly about this: it would be non-trivial to stop this happening, as it would require either changing the library we use to handle field overflow on small screens, or rewriting that library. 

Closing issue as I doubt this'll be worth addressing any time soon
