### ISSUE TITLE
Beta banner 

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/grantnav#105]
Request to put the

> word 'beta' or 'alpha' on it prominently

This might be graphical - cc/ @notshi

**Comment by notshi** [comment]
Examples

![beta001](https://cloud.githubusercontent.com/assets/1515961/18137588/d7679f06-6fa0-11e6-9ad5-5fdb34992d5a.png)

![beta002](https://cloud.githubusercontent.com/assets/1515961/18137589/d780242c-6fa0-11e6-9c52-1c191cfabb96.png)
