### ISSUE TITLE
New freetext search with pre-selected facets - no results

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/grantnav#107]
I've searched for 

> "National Churches Trust"

I've then selected one of the Recipient Orgs listed (the first one)

http://grantnav-big.grantnav-dev.default.opendataservices.uk0.bigv.io/search?json_query=%7B%22query%22%3A+%7B%22bool%22%3A+%7B%22must%22%3A+%7B%22query_string%22%3A+%7B%22query%22%3A+%22%5C%22National+Churches+Trust%5C%22%22%7D%7D%2C+%22filter%22%3A+%5B%7B%22bool%22%3A+%7B%22should%22%3A+%5B%5D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%7B%22term%22%3A+%7B%22recipientOrganization.id_and_name%22%3A+%22%5B%5C%22National+Churches+Trust%5C%22%2C+%5C%22GB-CHC-1119845%5C%22%5D%22%7D%7D%5D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%5D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%5D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%5D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%5D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%5D%7D%7D%5D%7D%7D%2C+%22aggs%22%3A+%7B%22recipientRegionName%22%3A+%7B%22terms%22%3A+%7B%22size%22%3A+20%2C+%22field%22%3A+%22recipientRegionName%22%7D%7D%2C+%22recipientDistrictName%22%3A+%7B%22terms%22%3A+%7B%22size%22%3A+10%2C+%22field%22%3A+%22recipientDistrictName%22%7D%7D%2C+%22recipientOrganization%22%3A+%7B%22terms%22%3A+%7B%22size%22%3A+10%2C+%22field%22%3A+%22recipientOrganization.id_and_name%22%7D%7D%2C+%22fundingOrganization%22%3A+%7B%22terms%22%3A+%7B%22size%22%3A+10%2C+%22field%22%3A+%22fundingOrganization.id_and_name%22%7D%7D%7D%7D

If  then try to do a new freetext search (for youthnet), I get no results:

http://grantnav-big.grantnav-dev.default.opendataservices.uk0.bigv.io/search?json_query=%7B%22query%22%3A+%7B%22bool%22%3A+%7B%22must%22%3A+%7B%22query_string%22%3A+%7B%22query%22%3A+%22youthnet%22%7D%7D%2C+%22filter%22%3A+%5B%7B%22bool%22%3A+%7B%22should%22%3A+%5B%5D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%7B%22term%22%3A+%7B%22recipientOrganization.id_and_name%22%3A+%22%5B%5C%22National+Churches+Trust%5C%22%2C+%5C%22GB-CHC-1119845%5C%22%5D%22%7D%7D%5D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%5D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%5D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%5D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%5D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%5D%7D%7D%5D%7D%7D%2C+%22aggs%22%3A+%7B%22recipientRegionName%22%3A+%7B%22terms%22%3A+%7B%22size%22%3A+20%2C+%22field%22%3A+%22recipientRegionName%22%7D%7D%2C+%22recipientDistrictName%22%3A+%7B%22terms%22%3A+%7B%22size%22%3A+10%2C+%22field%22%3A+%22recipientDistrictName%22%7D%7D%2C+%22recipientOrganization%22%3A+%7B%22terms%22%3A+%7B%22size%22%3A+10%2C+%22field%22%3A+%22recipientOrganization.id_and_name%22%7D%7D%2C+%22fundingOrganization%22%3A+%7B%22terms%22%3A+%7B%22size%22%3A+10%2C+%22field%22%3A+%22fundingOrganization.id_and_name%22%7D%7D%7D%7D

I understand that this would be because I have a filter (on Recipient Org) pre-selected - which illustrates a use case whereby this function might not be helpful...

**Comment by robredpath** [comment]
Closing in favour of #132.
