### ISSUE TITLE
Contrast of colors - when projecting GrantNav

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/grantnav#109]
When showing GrantNav to people via a projector (albeit usually very good ones) I've observed that the light grey (used for the total results number and the date of grant) isn't very visible.  We might want to look at the contrast

There's a similar issue with the pre-selected search links on the home page - they are difficult to spot

I'm aware that we didnt test GrantNav on walls so far

--> @notshi

**Comment by caprenter** [comment]
This was also reported as a problem on a big screen.

**Comment by stevieflow** [comment]
In the workshop in Manchester yesterday we had an old projector / touch board type thing.  It was very close to being black and white!  Hence, the contrast (or lack of) meant some aspects were difficult to see

**Comment by robredpath** [comment]
This might also be an accessibility consideration
