### ISSUE TITLE
Facet by grant value

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/grantnav#11]
Add a facet to filter the search results by Amount Awarded

**Comment by caprenter** [comment]
I think @kindly has done some thinking on this already. I suspect we will either be shown something, or thoughts will appear here

**Comment by stevieflow** [comment]
Yes, I agree - @kindly talked about this, so look forward to working on it from there

**Comment by kindly** [comment]
This is done here 7fc4ee51229189c332d5804c2bda5e2c5df5e7d5
