### ISSUE TITLE
Facet by date

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/grantnav#12]
Facet search results by the date of grant awarded

We may choose to undertake this by pushing the data into the relevant calendar year, and providing these as the facets

**Comment by caprenter** [comment]
stevieflow - would you be able to try to find out what might be useful to people. I'm thinking Calendar year is one option, but quarters might be good, or is April - April financial year still a thing that makes sense?

Another option that might be worth exploring would be start and end date (pickers)

There are other dates that might also be considered - (planned and actual) (start and end dates)

Datemodified might also be a useful search - grants that have changed in the last 3 months for example.

**Comment by stevieflow** [comment]
We currently know that *all* records should have a date for the awardDate field - end date/last updated date is not so widespread

Therefore, I would suggest that we agree to concentrate on the awardDate field first of all

I think financial year would make most sense in iteration 2.  With that in use, we can explore more in terms of what people find useful - but think trying to establish that initially would be cumbersome (I will ask though)

**Comment by stevieflow** [comment]
NB - 170169 / 173302 have awardDate - so coverage is not 100% -- we might then need to think how any facet can also include a [no date] option

**Comment by stevieflow** [comment]
Feedback from GC:

I would just go for calendar year for now.  My guess is that this will be a pretty rough and ready indicator - the difference between calendar and financial years may be too fine grained for most users.

If possible rather than specifying the actual year I'd go for something like:
- within past twelve months
-within past three years
- more than three years old.

**Comment by stevieflow** [comment]
Some other feedback received:

> My gut reaction is that although the government uses the financial year of April-March

> Otherwise it might not be that helpful and we could stick to calendar year, which we know won't require explaining.

**Comment by kindly** [comment]
Done here 11ae5787f6cdfddf58c4c38d0811243e564efc94
