### ISSUE TITLE
As an analyst I want to be able to count grants awarded or sum total amounts of money within a given set of criteria to produce reports for managers    

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/grantnav#125]

**Comment by robredpath** [comment]
This is putting table-page-style aggregate results on search result pages

**Comment by robredpath** [comment]
Make the numbers easier to see - the current font is unclear

**Comment by robredpath** [comment]
Note: no average

**Comment by stevieflow** [comment]
For area pages we have the following - with a couple of omissions on the funder/recipient pages:

Total grants
Total recipients
Total funders
Total awarded
Average awarded
Largest award
Smallest award
Earliest award date
Latest award date

This should give us enough to discuss what we put in place for search results

**Comment by robredpath** [comment]
Satisfied by #169
