### ISSUE TITLE
As a grant assistant I need to feel confident that if it feels like a “dead end” it’s not because of MY incompetence its because the data’s not there in order not to lose confidence in using it.  X4

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/grantnav#126]

**Comment by stevieflow** [comment]
Also: 

As a GrantNav user, I want to be aware of when data limitations will limit my ability to refine my search results

**Comment by robredpath** [comment]
#198 and #208 should satisfy this. We might want to add a 'no results found' message for blank sets - or do we already do this?

**Comment by robredpath** [comment]
The 'no results' page doesn't have facets. This is confusing!

**Comment by robredpath** [comment]
We styled the 'no results' page to have facets and that resolved this issue
