### ISSUE TITLE
As an analyst or data advocate I want to be able to export data or lists of results to use for a variety of follow up purposes such as reports and presentations  x10

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/grantnav#127]

**Comment by robredpath** [comment]
This is:
- incorporating a download button into both displays of grants
- download includes all data that we know about those grants, not just what's displayed
- using human-readable column headings
- CSV and xlsx supported
- might be using a URL derived from the current URL to download
- button is greyed out on results sets larger than X
- links to where to get the rest of the data (ie, 360 list)

**Comment by stevieflow** [comment]
As a starter, I've attached what could be considered the fields for this

NB: On location - I've added in columns for the Recipient Org lookups that we do in Grant Nav (ward, local authority * region).  For now, I've left in some of the Beneficiary Location columns - to discuss

I've also made a note that "data source" column would be our data source - different from the value in the source data

I also added a column "Publisher: Name" - 

We might take the view that to begin with we export even fewer columns, to get people using it and giving feedback.

[export-DRAFT.xlsx](https://github.com/OpenDataServices/grantnav/files/316229/export-DRAFT.xlsx)

**Comment by stevieflow** [comment]
(oh - this sheet should be called "grants" I think - although I could not attach a csv to the Issue

**Comment by Bjwebb** [comment]
"Data Source" is in there twice. If you actually want both possibilities for this, then a different name for one would make sense.

These are the headers that don't correspond to a field in the standard:
* Publisher: Name
* Recipient Org: Ward code
* Recipient Org: Ward Name
* Recipient Org: LA Code
* Recipient Org: LA Name
* Recipient Org: Region Name
* Recipient Org: Region Code

For publisher name, it makes sense that this is additional to the standard.

For area names and codes, there is a way doing this in the standard - so it looks odd for us to be doing something different here. If we want to output the columns like this, then it might be worth thinking about whether we should be changing the standard also.

**Comment by stevieflow** [comment]
Thanks @Bjwebb 

``Data Source`` maybe my error, as I added it and then realised there was already one!  I dont see this field overly used by publishers, so would suggest we populate it ourselves, with our source URL, and then only have it once in the file

In terms of the location columns, then thanks for your observation.  I was also thinking about what the user sees in GrantNav, but appreciate that these would be labelled differently in the standard

I guess if we went with the standard headings we woudl also include an AreaType column for each area.  Question would be - do we store these values anywhere (or need to?)?

**Comment by stevieflow** [comment]
Note: We should add to the the "official name" from Charity Commission --> https://github.com/OpenDataServices/grantnav/issues/163

**Comment by robredpath** [comment]
Satisfied by #172

**Comment by robredpath** [comment]
@Bjwebb @stevieflow Did you guys come to an agreement on the fields for this?

**Comment by stevieflow** [comment]
@robredpath I dont think we did - but I did ask @Bjwebb in https://github.com/OpenDataServices/grantnav/issues/127#issuecomment-226761832

> Question would be - do we store these values anywhere (or need to?)?

**Comment by robredpath** [comment]
I talked to @Bjwebb earlier and we're inclining towards naming these fields in such a way so as to make it clear that they're augmented data rather than original data

**Comment by Bjwebb** [comment]
I've tried to make a copy of the template that more closely matches the standard [export-DRAFT-standard.xlsx](https://github.com/OpenDataServices/grantnav/files/334427/export-DRAFT-standard.xlsx) (although not 100% sure the codes are correct).

> I guess if we went with the standard headings we woudl also include an AreaType column for each area. Question would be - do we store these values anywhere (or need to?)?

Yes that's right. No I don't think we need to store them as such, we should be able to derive them from the code prefixes.

**Comment by stevieflow** [comment]
I agree with the new template from @Bjwebb

**Comment by stevieflow** [comment]
Checking the current export file - I think we're missing a column for licence?  This is (most) probably vital for provenance too ....?

**Comment by robredpath** [comment]
I've added #191 to make sure that we don't lose this
