### ISSUE TITLE
As Dustin when I have a set of results, and then perform a different manipulation I want to understand what will happen – eg will it add to the existing results, or start a new search  x4

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/grantnav#132]

**Comment by stevieflow** [comment]
Worth noting (via #78) that one implementation on this could include a space to print / confirm which facets have already been selected 

eg: 

![facet](https://cloud.githubusercontent.com/assets/1209944/16238796/c9478368-37d9-11e6-91d7-59c3ff1cbf12.png)

**Comment by robredpath** [comment]
See https://github.com/OpenDataServices/grantnav/issues/107 for a case of where this is an issue

**Comment by robredpath** [comment]
#208 and #209 should help a lot with this
