### ISSUE TITLE
As team grantnav I want to capture search strings in analytics so I can see how people are using the site

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/grantnav#146]

**Comment by Bjwebb** [comment]
We've been looking into this in https://github.com/OpenDataServices/grantnav/issues/21

**Comment by Bjwebb** [comment]
We now log search text http://mon.opendataservices.coop/piwik/index.php?module=CoreHome&action=index&date=previous30&period=range&idSite=6#?module=Actions&action=indexSiteSearch&date=previous30&period=range&idSite=6

We're not logging anything to do with the facets.
