### ISSUE TITLE
Create grant page

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/grantnav#15]
Endpoint for all details on any grant

**Comment by caprenter** [comment]
I guess there is work here on working out what the URL should be for these pages - there should not be duplicate grant identifiers (there will be tho!).

Then I probably want to see:
1) Everything you can tell me about that grant
2) Links to other stuff I might be interested in

I might also want to get back to the search results - will the back button do this for me, or do I need something more?

1) Everything you can tell me about that grant
For now I'd be happy to see all the info we have on that grant - not bothered about style just yet. I'm thinking this is just all the fields that we know about.
Wondering if we should try to mock up all fields and then just populate what we can?

2) Links to other stuff I might be interested in
Probably need to try to link to other 'directly linkable data' - e.g. the Publisher, The Recipient Org

We might also want to try some links to 'more grants like this' (bearing in mind the data might not support this) - more grants in Manchester, more grants from this publisher (is this search results or a publisher page? Is that the same thing?)

**Comment by stevieflow** [comment]
I think @caprenter has captured everything

In terms of possible fields, we should note that these are currently output in the search results, for each grant

**Comment by caprenter** [comment]
Thanks @Bjwebb - lets see what feedback we get. I know people have asked for links back in the past. I just wanted to check that back button functionality wasn't broken for any odd reasons.

**Comment by Bjwebb** [comment]
We now have a grant page, e.g. http://grantnav.grantnav-dev.default.opendataservices.uk0.bigv.io/grant/360G-blf-AVR_1_010140024 but at the moment it's just what was previously in the search result page.

**Comment by stevieflow** [comment]
The grant page is "created" - so this issue can be closed?

**Comment by Bjwebb** [comment]
Possibly, although there's some thoughts in this issue that might want to be captured.

**Comment by stevieflow** [comment]
Ill move to iteration 3 to progress therefore

**Comment by stevieflow** [comment]
@caprenter I'd be keen to close this issue

Via https://github.com/OpenDataServices/grantnav/issues/15#issuecomment-189294731 you list some other aspects.  Shall we try and pick these out into new issues?

**Comment by robredpath** [comment]
Closing - the minimal implementation of this is done, and the other aspects are ones that we've discussed elsewhere.
