### ISSUE TITLE
Decide on which way to do 'amount awarded' and remove the facet that we don't want

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/grantnav#154]
Partially satisfies #204

**Comment by robredpath** [comment]
@stevieflow do you have opinions on this? 

The amount awarded facet could be smarter - log scale perhaps?

**Comment by stevieflow** [comment]
I have no preference - Geoff might

What do users say?

**Comment by robredpath** [comment]
Geoff suggested the log scale

The feedback from users is that having two is confusing. In London there was some discussion over whether a pair of sliders and/or free entry boxes might be more use, as it's more likely that users will want to find grants in a particular range that their organisation is interested in.

**Comment by robredpath** [comment]
Replace the Amount Awarded with two boxes for a custom range, rename Amount Awarded Fixed
