### ISSUE TITLE
As a staff member at a funding org, I want to be able to download aggregate data about search results on my own data

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/grantnav#157]
Eg a single org using GN on their own data to find funding gaps

**Comment by robredpath** [comment]
This is already done by iteration 5's search stats work, I think

**Comment by Bjwebb** [comment]
We're collecting some search information. We don't really collect which publisher's data people are looking at though.

I'm also not sure what of it we'd actually want to make available to funders though (privacy concerns etc.).

**Comment by robredpath** [comment]
This is about publishers using GN to study their own data rather than analytics.

**Comment by robredpath** [comment]
e.g. a publisher might want to see their total grants over 3 years broken down by region

**Comment by Bjwebb** [comment]
Oh, I see.
