### ISSUE TITLE
Header doesn't render properly on IE 

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/grantnav#164]
![screen shot 2016-06-09 at 12 43 45](https://cloud.githubusercontent.com/assets/641009/15928618/d7b02728-2e3f-11e6-8043-0ce3967ce5e6.png)

**Comment by Bjwebb** [comment]
What version of IE is this?

**Comment by robredpath** [comment]
IE8 / Win7

It works fine in MS Edge on Win10

**Comment by Bjwebb** [comment]
Would be useful to know if this problem exists in IE11. As of January that's the only IE that hasn't reached End of Life - https://www.microsoft.com/en-gb/WindowsForBusiness/End-of-IE-support. (Although what probably matters more is how many people in the third sector are still using it...)

**Comment by robredpath** [comment]
I'll try it out on some other versions - it's so much easier now MS ship VMs with windows and IE! But, as you say, it's what people are using that matters, and I suspect that IE8/Win7 is a pretty common combination. We can track it when we start getting some users, but I'd be amazed if we have few enough old IE users that we don't need to support it.

**Comment by caprenter** [comment]
I've checked this in IE11 and it all seems ok to me

**Comment by robredpath** [comment]
When users have hit this in testing, they've used a different browser. Not ideal but not a priority compared to some of the other things we've got on. It'll be interesting to see analytics when this goes live and we can look at using some support/hosting time to attend to issues if necessary

**Comment by morchickit** [comment]
@robredpath  to check if this still happens and if someone actually uses this version

**Comment by robredpath** [comment]
Although Windows 7 is the most popular OS among our users, the vast majority of visitors use Chrome or IE11. Only one person has used IE8 in 2017, so I think we can safely ignore this.
