### ISSUE TITLE
When multiple organisations share a charity number, facets show the name of the first one that the code encountered

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/grantnav#167]
Satisfies #163 

<img width="274" alt="screen shot 2016-06-21 at 15 29 22" src="https://cloud.githubusercontent.com/assets/641009/16233079/f644ab26-37c4-11e6-90ad-ea34067c6c1d.png">

**Comment by robredpath** [comment]
Implementation: download the list of names from charity commission, use that for facets

**Comment by robredpath** [comment]
I'll do this, I'll need @Bjwebb 's help wiring up the facets though

**Comment by robredpath** [comment]
@ekoner did you create a charities commission data source at some point? Could you share that work with me - it'd be useful for this? 

I think @kindly is going to have to actually implement this though, I've not been able to get to it this week :/

**Comment by ekoner** [comment]
@robredpath The May 2016 extract_charity is here: https://drive.google.com/file/d/0B_hfAR6BAnvYS1JtTS1kdFlFdVk/view?usp=sharing
You'll want to read the guidance here: http://data.charitycommission.gov.uk/data-definition.aspx

Charity Commission publish open data as bcp (SQL Server) files, there's a script for converting from NCVO which I've beefed up with some additional checks. Shout if you need it.
