### ISSUE TITLE
Show  x , y z results - paging

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/grantnav#17]
For the search results , add a function to be able to display more/all search results - similarly to what we did in https://github.com/OpenDataServices/cove/issues/221 for CoVE

**Comment by caprenter** [comment]
This needs some thought. A search on 'gardens' produces 6516 results at the moment.

I'm not sure what is useful here except to perhaps refine your search.

However, the current paging does not tell you how many results you are seeing e.g.
"Showing 1-10 of 6516"
but I'm also not sure how useful that really is.

We might consider offering paging buttons at the top of the page as well as at the bottom.

We might consider offering more options about the number of results per page. 

It would probably help if we understood how people want to search this data.

**Comment by stevieflow** [comment]
I guess it would initially be useful to understand if it is possible to list all the results (even if it is 6516) for any query, out of teh box?  In other words, what have we currently done to limit the results we see in this version?

**Comment by robredpath** [comment]
Closing - we're supporting the 'get all the results' use case through a download in #172 

We might want to revisit the question of how many results to display on each page, but I didn't hear anyone comment on it at the user workshop. I think I only really care about how many results appear on a page when I'm looking for something that the facets don't let me refine by, or I'm working my way through a list, neither of which a user's likely to be doing with GrantNav
