### ISSUE TITLE
As a user, I'd like to see appropriate placeholder text when fields are empty so that I'm reassured that the issue lies with the data

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/grantnav#170]
Satisfies #136

When a description field is blank, a message that “No description has been provided for this grant” should be displayed

This is still pending feedback from @stevieflow as we need to resolve the issue of whether data that's missing required fields can actually be imported into GrantNav

**Comment by stevieflow** [comment]
I dont think I can answer:

> whether data that's missing required fields can actually be imported into GrantNav

I thought @bjwebb was  going to look into this , in terms of how/what data is loaded (we have a planio ticket - 5088)

**Comment by robredpath** [comment]
The parts of this which caused issues are dealt with by us only allowing valid data
