### ISSUE TITLE
As a user, I'd like the grants details page to have human-readable labels for the fields

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/grantnav#171]
The JSON forms of the field titles aren't particularly friendly to non-technical users. We should provide the human-readable forms instead, where possible. If possible, we should continue to provide the JSON titles as well, potentially in smaller/lighter/monospaced text to set them apart

**Comment by robredpath** [comment]
Satisfies #123

**Comment by robredpath** [comment]
User feedback: it would be good for the duration field to specify that it's in months

**Comment by robredpath** [comment]
We can't produce human titles for fields that aren't in the standard.

**Comment by robredpath** [comment]
We might want to prefix custom fields with Custom Fields: <JSON NAME>

**Comment by Bjwebb** [comment]
We need to think about what we want to do with "recipientDistrictName" and "recipientRegionName".

**Comment by robredpath** [comment]
Why are those special, @Bjwebb ?

**Comment by Bjwebb** [comment]
I think these are the names used for our derived location information atm.

**Comment by robredpath** [comment]
Ah, I see! I think that given that the user story is that people feel that the grants page is unfriendly as a result of all the JSON names, it makes sense for us to provide a human-friendly name. 

Should we add those fields to the standard? 
Or just add some sort of clue to the page that they're non-standard fields?

**Comment by Bjwebb** [comment]
This relates to what we call the fields in the CSV, see https://github.com/OpenDataServices/grantnav/issues/306

**Comment by Bjwebb** [comment]
In https://github.com/OpenDataServices/grantnav/commit/3d5f20652aed798e134a9e2f51b62557e46222b7 we solve this by adding them to a separate box (with custom titles).
