### ISSUE TITLE
As an analyst or data advocate I want to be able to export data or lists of results to use for a variety of follow up purposes such as reports and presentations

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/grantnav#172]
Satisfies #127

The single most common thing that we heard at the user workshops was that people wanted a way to obtain a dataset that they could then process further. Examples of this are:
- assessing the decisions that other funders made for similar applications (eg, “I’m assessing an application from a skate park in Leeds, how much have other skate parks in Leeds had? What about West Yorkshire? How about other mid-sized cities in the North?”)
- anting to obtain a list of candidate organisations to approach for further funding based on certain criteria (eg “I want to see a list of small organisations in Bradford who I can approach to discuss X”)
- reporting on what comparable funders are doing (eg “Here is how other large funders have distributed funds compared to how we have distributed funds”)
- to explore their own data (eg, “I want to produce a regional breakdown of how we spent our money year-on-year”). 

Some of these are use cases that are made much easier by GrantNav compared to doing similar work by hand in Excel, while some are actually novel. 

We should (in broad priority order):
- incorporate a download button into both displays of grants (search results and tables of grants) that generates a download of all data that we know about those grants, not just what's displayed (ie, all or most of the grant record)
- using human-readable column headings (as per the standard, where possible)
- We might want to use a URL derived from the current URL to download, to enable easier sharing
- JSON, CSV and xlsx supported
- The button should be greyed out on results sets larger than X. X is to be determined by experimentation. 
- There should be links to where to get the rest of the data (ie, the registry page on the 360 site)

We still need to decide on the fields that we're going to support for this. 

@Bjwebb have you decided on an implementation for this?

**Comment by robredpath** [comment]
xlsx is a would-be-nice, given that we're not using any of the features of that file format over CSV

**Comment by robredpath** [comment]
Outstanding issue: the standard doesn't represent the augmented location fields very well. We might want to change the standard, or make the output standard-compliant. @Bjwebb to mock up the latter and we'll take it from there.

**Comment by robredpath** [comment]
JSON download is simple in a basic form, but the complexity is telling the difference between the original fields and the augmented data. The augmentation is entirely addition, so we should ensure that it's clear what's been added.

**Comment by robredpath** [comment]
What we're doing about provenance / rest of the data will depend on how we do #166

**Comment by robredpath** [comment]
The output should be able to be licensed as share-alike

**Comment by robredpath** [comment]
Implementation - probably don't use flatten-tool; just create a view that iterates over the JSON and outputs CSV (or full JSON)

**Comment by robredpath** [comment]
@Bjwebb to look at the title stuff, I'll do the rest

**Comment by Bjwebb** [comment]
If we're only outputting the first item of an array in the CSV (and on the site), we should know when people start supplying more than one item in these arrays so we can adapt.
