### ISSUE TITLE
User feedback: The URLs (if valid) should be clickable

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/grantnav#173]
When a grant record includes a URL in the Other Data table - for ``recipientOrganization: url`` or ``dataSource`` then this should be clickable

This should open in a new tab/window?

Example: 360G-esmeefairbairn-10-2623

cc/ @ekoner

**Comment by Bjwebb** [comment]
Is this a duplicate of https://github.com/OpenDataServices/grantnav/issues/103 ?

**Comment by stevieflow** [comment]
oh dear - sorry - duplicate of #103 - thanks @Bjwebb
