### ISSUE TITLE
Dealing with invalid data

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/grantnav#183]
We've not yet decided whether we should really be loading invalid data or not.

However, in the short term, the published big lottery data is invalid, but people want to demo with this data in. I've made some tweaks so that the things I know break now work: https://github.com/OpenDataServices/grantnav/commit/291bdd14dff9b2a10e90d453abf9d1915918853c

We might want to handle this differently going forward.

**Comment by robredpath** [comment]
@Bjwebb the official word is that only valid and properly licensed data should be loaded in production. I've flagged that this means that Esmee data is currently excluded

**Comment by stevieflow** [comment]
This can be closed, I think?
