### ISSUE TITLE
As a developer, I want to be able to obtain data programmatically so that I can develop new applications and meet needs that GrantNav doesn't

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/grantnav#184]
One of the ways in which 360Giving is valuable is that as well as ensuring that information that wasn't previously available is now published, it's published in a way that means that it can be programmatically combined to form a larger data set, and applications can be built that leverage that dataset to do new and useful things. 

However, the current state of the 360Giving data is that there are still significant technical barriers to having that larger data set available for re-use - to get from zero to a Python dict or Ruby hash containing 360Giving data from several publishers requires significant development effort - we know this all too well from building the datagetter for GrantNav. By increasing the cost of getting started with 360 data, we make it harder for developers to experiment and build out PoCs.

We should assist developers in their attempts to programmatically access 360Giving data.

**Comment by robredpath** [comment]
Satisfied by #210

**Comment by caprenter** [comment]
We should also be aware that for small sets of data, or specific use cases, going directly to the source is also a developer need. 

We should be wary about making GrantNav the only/preferred access point to 360Giving data. It should be understood that GrantNav is an opinionated consumer of and remixer of 360Giving data. 

There is documentation for developers on how to access source 360Giving data here: http://www.threesixtygiving.org/data/find-data/ 

There are also re-usable tools that are quite easy to follow and/or modify for other developer needs. [Datagetter](https://github.com/ThreeSixtyGivings/datagetter) is not very complicated.

[Flatten Tool](https://github.com/OpenDataServices/flatten-tool) is perhaps more complicated, but is can easily be incorporated into other projects if developers prefer to go to source for their data.

I'm not saying people should not have access to GrantNav data programatically, but that we should be aware of how this is different from 'all 360Giving data', and that develops have other data needs over and above those provided by GrantNav.
