### ISSUE TITLE
Confusing spacing and arrangement of JSON and CSV download icons

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/grantnav#192]
We should put the CSV icon first, so that LTR readers scanning come across the more familiar button first. 

We should increase the gap between the buttons slightly, to make the separation more obvious

We should adjust the icons to ensure that the space between the graphic and the text is the same for both.

**Comment by caprenter** [comment]
See: http://grantnav.threesixtygiving.org/funder/360G-blf
