### ISSUE TITLE
Grant amounts should have commas every 3 digits for readability

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/grantnav#196]
eg 10000 grants should be rendered as 10,000 grants in table views

**Comment by caprenter** [comment]
I'm happy to investigate this. Do you want to assign to me and put into the next sprint?

**Comment by robredpath** [comment]
Great, thanks!

**Comment by caprenter** [comment]
I can't find any examples of where this is not already the case. Does it still need fixing?

**Comment by robredpath** [comment]
I can't find any either. Maybe this got fixed silently? Either way, I think it's done.
