### ISSUE TITLE
"human readable" URLs

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/grantnav#20]
(pciked up via #15)

Some investigation in terms of how we enable URLs structures might be useful - 

eg 

grantnav.thing/grant/1234
grantnav.thing/org/1234

Mainly - what / how would we do this (rather than how they are structured)?

**Comment by robredpath** [comment]
Closing - we've got nice URLs for orgs and grants. 

Nice URLs for search (and API) are a whole other question, but will be related to #155
