### ISSUE TITLE
Charity Commission data

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/grantnav#202]
Do we need to credit the charity commission data that we are using to resolve names somewhere.

Do we need to pay attention to the licensing of that data for anything else we do in the application e.g. downloads? https://github.com/OpenDataServices/grantnav/issues/191

**Comment by Bjwebb** [comment]
We do, in the footer:

> Contains Charity Commission data © Crown copyright and database right 2016

**Comment by caprenter** [comment]
I think we need to update [LICENSE.rst](https://github.com/OpenDataServices/grantnav/blob/master/LICENCE.rst)

To say that the data in https://github.com/OpenDataServices/grantnav/blob/master/dataload/charity_names.json
 is pulled from:
http://data.charitycommission.gov.uk/default.aspx

which is licensed "All content is available under the Open Government Licence v3.0, except where otherwise stated"

**Comment by caprenter** [comment]
So the footer is covered. I'll go ahead and update the LICENSE.rst
