### ISSUE TITLE
As a user, I should be able to expand or collapse the LH UI and have it in a more sensible order

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/grantnav#205]
Partially satisfies #204

The LH UI can get long and unwieldy, particularly on small screens. The two ideas that we've had to fix this are to make the facets expandable, or to make the LH facet list scroll independently from the rest of the page. We should see if there are other options, discuss which option is best (considering dev time and UX factors) and implement one.

**Comment by robredpath** [comment]
Solving this issue by re-ordering to put commonly used facets at the top, removing one of the amount awarded facets to make it less scrolling, investigating expandability

**Comment by robredpath** [comment]
@stevieflow - do you have any idea what the top facets should be? ie, which do people want to use first?

**Comment by stevieflow** [comment]
I've observed people skip past the funding and recipient org facet - as they are interested in geography / value and date more.  

There might be an argument to reposition the organisation facets... somewhere!

**Comment by robredpath** [comment]
Move the year to the top, reduce to 3 rows and add a 'see more'
