### ISSUE TITLE
As a user arriving at the site, I want to be able to choose whether to search for a specific thing or make a general search

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/grantnav#207]
Satisfies #206

A lot of confusion arises when trying to complete a task of the form "As a grants officer, I want to check the funding history of an organisation". Lots of organisations have common words in their names (eg 'arts centre' or 'school') and therefore will return results for subsets of their names. 

Likewise, a research analyst looking for all grants in a particular place will hit issues with free text search - "bristol" returns both grants made in Bristol and grants made for trips to Bristol. 

If we knew what people were looking for earlier in the process, then we could give them much better results. BUT, we don't want to make it too hard to start using the app or get in the way of other use cases. 

We should rework the front page to allow people to specify if they're looking for an organisation (maybe distinguishing between a funding org and a recipient org) or a place, or if they want to carry out a free-text search. Ideas for this have included:
- A drop-down to the right of the search box
- Different search icons
- Help text that sets up the search box with the appropriate options (eg "You can search for a _location_, _organisation_...." where each link sets up the search box appropriately)

An acceptance criterion for this is that we need to make sure that people's tendency not to read anything on websites isn't overlooked - the feature must be both possible to use and likely to be used by users following the story above. Like a joke, if you have to explain UI, it's not good UI. 
 
Implementation-wise, we probably want to do this using the elasticsearch filters eg recipientOrganization.name:battersea - even though this doesn't set up the facets, it gets the user much closer to what they're looking for.

**Comment by robredpath** [comment]
We need to be conscious that the 'main' search box searches grants, and there are other search boxes

**Comment by robredpath** [comment]
Currently, only recipientDistrictName:"City of Bristol" will get you results, just 'bristol' won't. We need to add another field that can be searched.

**Comment by robredpath** [comment]
I'll talk to Shi and work out if there's a way to make some sort of selector on the front page look good. Otherwise, we'll do it on the results page.

**Comment by robredpath** [comment]
We could improve this by adding more augmented data - county, geocode?

**Comment by caprenter** [comment]
We could also look at the text:
Try these examples: volunteers, heritage, disabilities - and make the example terms educate the users about how to search - e.g. "Battersea Arts Centre", Region:Yorkshire and the Humber, etc

**Comment by robredpath** [comment]
As far as I understand, we're not currently looking at supporting Region:Yorkshire and the Humber in that form

**Comment by robredpath** [comment]
We're happy to look into doing something clever, depending on what we hear back on UI
