### ISSUE TITLE
Log search queries

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/grantnav#21]
Can we log/store the search quesries people make?

We might not wish to display /render / use these right now, but it would be good to know if we can store and access them

**Comment by kindly** [comment]
If we are going to do this we would probably make our web analytics i.e piwik do this.  
We do not want grantnav itself storing anything as its best too make an instance of it as disposable as possible.

**Comment by caprenter** [comment]
I'd be keen to see this in place sooner rather than later so that we can at least get a handle on it. During development I think I'm happy to see all queries across all sites in the same analytics.

I've set up a site on our Piwik for this. Tracking code below.

Make sure this code is on every page of your website. We recommend to paste it immediately before the closing </head> tag.


<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(["setDocumentTitle", document.domain + "/" + document.title]);
  _paq.push(["setCookieDomain", "*.grantnav-dev.default.opendataservices.uk0.bigv.io"]);
  _paq.push(["setDomains", ["*.grantnav-dev.default.opendataservices.uk0.bigv.io"]]);
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//mon.opendataservices.coop/piwik/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 6]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript><p><img src="//mon.opendataservices.coop/piwik/piwik.php?idsite=6" style="border:0;" alt="" /></p></noscript>

**Comment by stevieflow** [comment]
Has this happened @caprenter @Bjwebb ?

**Comment by Bjwebb** [comment]
No

**Comment by stevieflow** [comment]
Would this enable us to log/record both

- traffic/visits 
- freetext search queries made

Or - is that two different scripts?

**Comment by Bjwebb** [comment]
@caprenter's script will log traffic/visits.

I think we can also use piwik to log "freetext search queries made", but I think it will require a little more configuration. I am planning to look into this though.

**Comment by Bjwebb** [comment]
I've added @caprenter's script from above, and deployed it to the two themed grantnav instances.

I don't think think this is going to work very well for tracking the text of search queries (although hard to be sure as piwik takes a while to populate). 
I've not had chance to look into setting piwik up to track this better.

FWIW, https://github.com/OpenDataServices/cove/issues/11 is a cove issue that may also want some custom piwik event stuff, so it may be worth considering the two together.

**Comment by stevieflow** [comment]
Thanks @Bjwebb 

We've now another deployed copy (with new BIG) - do we need to configure that too?

**Comment by Bjwebb** [comment]
@stevieflow No, as @caprenter suggested in https://github.com/OpenDataServices/grantnav/issues/21#issuecomment-191209782 all queries are currently going into the same piwik instance (and there's no extra setup for this).

**Comment by stevieflow** [comment]
OK great, thanks for clarifying @Bjwebb @caprenter 

I guess as "set-up" this can now be closed?

**Comment by Bjwebb** [comment]
I think this needs further work to resolve the core point of this issue, which is logging search queries.

We're logging the URLs people access, but search queries is rather difficult to get out of this.

**Comment by Bjwebb** [comment]
Looks like http://piwik.org/docs/site-search/#track-site-search-using-the-javascript-tracksitesearch-function may be the best way to do this.

**Comment by robredpath** [comment]
Satisfies #146

**Comment by robredpath** [comment]
Note that this may introduce cookies, which would require us to comply with the EU cookie directive

**Comment by stevieflow** [comment]
@robredpath re: https://github.com/OpenDataServices/grantnav/issues/21#issuecomment-227495617 - I guess we need a new issue for a cookie statement?

**Comment by robredpath** [comment]
I just closed one :D If this, or anything else, does introduce cookies then we can do the work around cookie control. I'm indifferent as to whether that spins out a new issue or not.

**Comment by robredpath** [comment]
Oops, closed the wrong issue earlier :D

**Comment by Bjwebb** [comment]
We now log search text http://mon.opendataservices.coop/piwik/index.php?module=CoreHome&action=index&date=previous30&period=range&idSite=6#?module=Actions&action=indexSiteSearch&date=previous30&period=range&idSite=6
