### ISSUE TITLE
As a developer, I should be able to download all the data from GrantNav as JSON via a REST-ish endpoint

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/grantnav#210]
Satisfies #184

**Comment by caprenter** [comment]
How is this data licensed for the developer to use?
What are the sources that were used to create the GrantNav data (and how were they licensed)?
How is the data different to the source data?

**Comment by robredpath** [comment]
This is getting pushed back to next sprint as it has dependencies on other work that we haven't finished yet
