### ISSUE TITLE
As a browser, I'd like a visual clue to understand how "complete" a grant record is

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/grantnav#220]
(From Manchester workshop)

I understand that some grants have more / different data than others.  When viewing search results and grant records, I'd like some indication as to how "complete" the data is.  This may be around a set of fields that are mandatory, or even extra fields that are included.

I'd like this indication to be visual - like a strength-meter type representation

**Comment by stevieflow** [comment]
(From Manchester workshop)

This may be the flipside: when a grant record is missing certain data fields, I'd like a visual clue to tell me.  This might be an !alert! icon - especially when data is below a certain criteria missing titles, descriptions, etc)

**Comment by stevieflow** [comment]
NB: logging these from the workshop for @robredpath to steward.  Appreciate they need more work

**Comment by robredpath** [comment]
Depending on what the decision regarding the data that actually gets loaded into GrantNav is, this may be less of an issue - if we say that only valid data gets in, then all the records will have at least the mandatory fields. 

An indication of coverage beyond that could be good though (ping @kindly !)
