### ISSUE TITLE
CSV and JSON download buttons in different places for Grants table

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/grantnav#222]
The CSV and JSON download buttons are in different places for the grants table on an area page (district/Guildford%20District - left aligned) and an org page (funder/360G-blf - right aligned)

As a user I'd expect them to be in the same consistent location

**Comment by robredpath** [comment]
They also need a bit more space between them to make them a bit easier to work with. @caprenter can you attend to this? I'm happy to do the Photoshop work as necessary
