### ISSUE TITLE
Favicon missing

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/grantnav#226]
There's no favicon on the site; while not critical, it's a nice thing to have to give the site a more polished feel

**Comment by robredpath** [comment]
@caprenter same deal with this as #227 - I can ask Shi to design a favicon as part of her 4 days if we feel that's a good use of her time? I don't really have a feel for how contentious a favicon might be - if we're happy for me to just stick together something simple in Photoshop, I'm happy to do that.

**Comment by caprenter** [comment]
I have no strong opinions here.

**Comment by robredpath** [comment]
This actually depends on the outcome of the conversation about how GrantNav sits relative to the rest of the 360 site, so let's wait before implementing anything here

**Comment by caprenter** [comment]
I think there should be something in place for 'live' - I'd suggest at least an orange G

**Comment by robredpath** [comment]
Agreed. I'll come up with something.

**Comment by caprenter** [comment]
Stumbled across this the other day: https://github.com/OpenDataServices/developer-docs/blob/master/tools-generic.md#favicons

**Comment by robredpath** [comment]
:D I found that - very useful! 

What do people think of:

![grantnav_favicon](https://cloud.githubusercontent.com/assets/641009/17775572/b9c7b5d0-6550-11e6-8d60-e715a12641cc.png)

**Comment by caprenter** [comment]
I think it's just the job!

**Comment by Bjwebb** [comment]
We now have a favicon.
