### ISSUE TITLE
Titles are entire query

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/grantnav#227]
The page title is the entire query, because we don't specify a title. Much like #226, this is a polishing consideration but would be good to do

**Comment by robredpath** [comment]
@caprenter , Shi noticed this when looking at the site for our conversation about her last 4 days with us. Do you have capacity to attend to it this week? No worries if not, we can always schedule it for iteration 7. Does it require any more detail?

**Comment by caprenter** [comment]
I need more detail - I've no idea what this means - can you paste a link or a screen grab pls?

**Comment by robredpath** [comment]
![screen shot 2016-07-25 at 13 16 43](https://cloud.githubusercontent.com/assets/641009/17101033/1862d5a6-526a-11e6-8870-32ee6f69f0a5.png)

**Comment by caprenter** [comment]
I don't know how to do this in a django way. I can edit base.html and write GrantNav in there if you wish.

I'll un-assign myself

**Comment by robredpath** [comment]
I think that would be acceptable - it's neater than what we currently have, and no less meaningful. Although it should probably be "360Giving GrantNav".
