### ISSUE TITLE
As a user arriving at the site, I want clear examples showing me how to do different things with the search bar

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/grantnav#235]
eg quoted search

**Comment by caprenter** [comment]
I've been thinking about this as well and was wondering if we need to put something front and centre about what GrantNav is, and what it is supposed to do - this might be the About page - https://github.com/OpenDataServices/grantnav/issues/57

but I'm also thinking about the user stories it is trying to satisfy, and how that might be different from caprenter sitting at Open Data Services using it - (especially the - use it to refine a data set and then download it story)

I was also thinking this could possibly done in the form of user story quotes.
"I used grant nav to home in on some data then downloaded it..." Mrs Trellis etc

**Comment by robredpath** [comment]
+1 for a user-story-centric approach to doing this.

**Comment by caprenter** [comment]
Just checking if I have indeed hijacked this thread. Does it need to be split into a new issue, and does it need to get promoted into the next sprint discussion?

**Comment by robredpath** [comment]
I think there's two bits to take forward here:

- Better help text that shows the various ways that the box can be used, including automagical location and recipient searches
- Some way of supporting the various narratives that users will want to take part in during their interaction with GN and how the tool works for those. I think this second piece is the one that should be split off to a new issue and brought into Next Sprint :)
