### ISSUE TITLE
Front page search workings

### ISSUE THREAD

**Issue by notshi** [OpenDataServices/grantnav#242]
@robredpath  Screenshots of alternative design to radio buttons - dropdowns.

![dd00](https://cloud.githubusercontent.com/assets/1515961/17254650/8ec37098-55ad-11e6-9e22-c87d88e7baf9.png)
![dd01](https://cloud.githubusercontent.com/assets/1515961/17254652/8ed3c9a2-55ad-11e6-96ee-ce19e712215a.png)
![dd02](https://cloud.githubusercontent.com/assets/1515961/17254651/8ec937f8-55ad-11e6-8e7a-e3d852169874.png)

I've also restyled the example links so they look more obvious. The grey colour links on orange is a tad hard to see. Hover states of those will likely be a background-colour change as well as (or not) underlined text.

You could also style the hover state for the 3 main data links with background-colour change as well.
![hover00](https://cloud.githubusercontent.com/assets/1515961/17255136/cc496254-55af-11e6-8bcc-ed2c9934b2fb.png)

If this is okay, I'll make the changes in a branch and check it in.

**Comment by robredpath** [comment]
Thanks @notshi . I was slightly worried that a left-hand dropdown would get missed but I think that does stand out. 

I love the reworked examples and the hover colour on the big numbers!

@stevieflow , what do you think?

**Comment by robredpath** [comment]
@stevieflow can we run the mockups past a couple of users?

**Comment by KDuerden** [comment]
I've been invited to comment. They are as follows.
I like the new look drop-down - big improvement on the small buttons. Also like the shading when hovering over thing for numbers at the bottom too - think this make it clear you can interact.
I don't like the yellow highlight for examples - the colour itself makes things look 70s in combo with the orange. The buttons being highlighted so strongly makes the alignment/positioning look odd - better aligned with search box?
'What are you searching for?" is italics so could examples text "volunteers, heritage, disabilities" be in italics too - to make a visual link?

**Comment by robredpath** [comment]
@notshi this is relevant to your interests

**Comment by notshi** [comment]
Thanks, both. Duly noted.
