### ISSUE TITLE
As a user arriving at the site, I want to know that my use case is catered for so that I feel confident using the tool

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/grantnav#246]
Carried over from #235, we should provide some clues on the front page that when users arrive with a certain use case in mind that it's supported

'I was also thinking this could possibly done in the form of user story quotes.
"I used grant nav to home in on some data then downloaded it..." Mrs Trellis etc!' - DC

**Comment by robredpath** [comment]
@caprenter something to bear in mind when writing new examples for the front page

**Comment by caprenter** [comment]
A way of doing this is explored in https://github.com/OpenDataServices/grantnav/pull/274

We actually need the user stories written up that we want to promote tho.
