### ISSUE TITLE
Grey out CSV/JSON buttons if data set is too big to download

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/grantnav#247]

**Comment by Bjwebb** [comment]
Our preferred means of fixing this is to make sure no data sets are too big.

**Comment by timgdavies** [comment]
An approach we *could* consider is the pattern of queuing downloads, and then either e-mailing the user when their download is ready, or simply making them wait for it to be generated.

Whilst this should only be used for much larger datasets, I think it is generally a reasonable pattern, and one users are used to.
