### ISSUE TITLE
Search by Grant ID returns many results

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/grantnav#250]
I tried a search for a grant by a specific identifier: 360G-LBFEW-111578

This returns 177,501 

I was only expecting to get either
1) 1 result
2) possibly more than one if there were duplicates

The one I wanted was at the top of the list, but that was not immediately obvious to me. I had to mouse over and look at the info bar of my browser to check.

Reporting as this 'seemed odd to me'

**Comment by caprenter** [comment]
..and I now realise that if I search with quotes then I can get to a single result.
So: "360G-LBFEW-111578" gets me to one result

**Comment by caprenter** [comment]
See also: 
https://github.com/OpenDataServices/grantnav/issues/235
https://github.com/OpenDataServices/grantnav/issues/235

I followed up my experiment by also searching for the title of the Grant: Grant to Luton Accommodation and Move on Project Ltd 

This gives interesting/useful results with or without quotes - but I think knowing of 'quotes functionality' is very empowering for users

**Comment by robredpath** [comment]
@caprenter this is probably worth talking about in your new examples

**Comment by caprenter** [comment]
We decided to deal with this by putting a quoted example on the front page
