### ISSUE TITLE
Create a script to check assumptions of data going into GrantNav

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/grantnav#252]
From https://github.com/OpenDataServices/grantnav/issues/166

**Comment by Bjwebb** [comment]
I've done some work on this in https://github.com/ThreeSixtyGiving/datagetter/blob/master/check_grantnav_assumptions.py

**Comment by robredpath** [comment]
@Bjwebb I'm reviewing GN issues to either put them back on the backlog or moving them to some sort of 'done' - be that actually done, never going to be done, or done-enough. Which way should this go?

**Comment by Bjwebb** [comment]
This is done, but needs documenting, doing that now.

**Comment by Bjwebb** [comment]
https://github.com/ThreeSixtyGiving/datagetter#checking-downloaded-data
