### ISSUE TITLE
Make sure that we have accessURL for all publishers

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/grantnav#254]
From https://github.com/OpenDataServices/grantnav/issues/166

This should be a page. Publishers should be encouraged to put appropriate info on this page

**Comment by stevieflow** [comment]
We think this should be OK - with the exception of Northern Rock, as we host their data (they dont exist anymore).  In that case we could put http://www.threesixtygiving.org/data/find-data/ - will confirm with @KDuerden

**Comment by KDuerden** [comment]
Northern Rock's website is still live - spend-down fdns tend to keep sites going as part of legacy - so it is possible to include http://www.nr-foundation.org.uk/

**Comment by Bjwebb** [comment]
Ideally accessURL should be a page that provides a link to, and information about a publisher's data, rather than their website homepage. I'm guessing Northern Rock don't have such a page though, so I'm not sure what the best link is. Currently the link would appear with the following text:

> Northern Rock Foundation has provided the following link for information about their data:

Since we don't have a link, we currently say:

> Unfortunately Northern Rock Foundation has not provided a link to information about their data.

This may be a true statement, and we might chose to leave that as is.

I'm not sure why this is labelled "Done". In addition to Northern Rock we currently lack accessURLs for Nominet Trust, Trafford Council, and Zing.

**Comment by stevieflow** [comment]
I've updated all records to now have an accessURL

@KDuerden has also written a report in Salesforce to list these - in order to check for future entries
