### ISSUE TITLE
Set up new hosting for GrantNav

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/grantnav#259]
- New Bytemark account
- Get approval from 360 for £280+VAT/mo spending on 2x12GiB and 1x4GiB servers
- Purchase servers, provision, set up appropriate DNS (when decision has been made on domain)
- Record procedures for deploy/rollout

**Comment by robredpath** [comment]
Lots of useful notes in https://opendataservices.titanpad.com/457

**Comment by Bjwebb** [comment]
This is set up, I think.

Remaining tasks are to make sure this is documented, and to remove the old servers once we're happy.
