### ISSUE TITLE
Move the search box on the results page into the orange header

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/grantnav#260]
![uploads/8a82a56c-41ce-4237-a6df-97ede9bb4eab/Screen Shot 2016-08-11 at 14.38.00.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F8a82a56c-41ce-4237-a6df-97ede9bb4eab%2FScreen+Shot+2016-08-11+at+14.38.00.png)

**Comment by robredpath** [comment]
@stevieflow what's the rationale for this?

**Comment by stevieflow** [comment]
Good question

Rationale - not having a top nav for GrantNav?

Impact would be to move items back up.  But - and Ill stress - I do not have a designer pov

**Comment by robredpath** [comment]
@stevieflow grantnav doesn't currently have any top nav, just a blank orange bar that heads the site. Is there concern that it's a waste of space, or unwanted negative space? I can see how it would move search results up a bit meaning that you get more on the page, though - it is the way that Google do it for that very reason. That may or may not be a good thing, especially given that GrantNav behaves in a fundamentally different way from Google (doing a search doesn't clear facets). There's also quite a bit more UI to fit into there - there's the dropdown and the 'new search' button, which might get a bit crowded.

**Comment by stevieflow** [comment]
OK - I can follow this, and accept that this might be a rash design change, not fully researched.

Propose to leave this open, but on the backlog (not for next sprint)

**Comment by robredpath** [comment]
+1
