### ISSUE TITLE
Load data into production instances

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/grantnav#263]
From https://docs.google.com/document/d/1xW-EdaHSCHE-vDhunrKFwhFFFo69odjSdcVRqcW03IE/edit# : 

Decision: What are the characteristics of data to be loaded to GrantNav? A decision is needed on 16th August 2016.

>> All data for GrantNav should be valid and have an acceptable licence

Decision: What data should we be loading in? We require a decision on this by 360 one month ahead of public launch to allow testing and to ensure that expectations are met. 

>> All data that qualifies for the valid and acceptable licence deployment

**Comment by Bjwebb** [comment]
I've loaded data downloaded on Tuesday into our new deployments.

Links to these at https://opendataservices.plan.io/projects/grant-nav/wiki/Deployed_copies
