### ISSUE TITLE
GrantNav font splits into double vision at full screen on ipad

### ISSUE THREAD

**Issue by KDuerden** [OpenDataServices/grantnav#264]
Screenshots from ipad - one from GrantNav and from 360Giving site so an issue with the font. I didn't get this issue on my android phone. ![img_0025](https://cloud.githubusercontent.com/assets/20462640/17592100/dc6d6cba-5fd8-11e6-8b11-72cf27d8a1fd.JPG)
![img_0026](https://cloud.githubusercontent.com/assets/20462640/17592101/dc6dc156-5fd8-11e6-9d7b-9d250f52b890.JPG)

**Comment by robredpath** [comment]
I have replicated this using Simulator in XCode

**Comment by robredpath** [comment]
This is due to the use of 'faux styles' using font-faces. When the browser can't find the 'real' bold version of a font, it tries to make one by rendering a second copy of the normal one.

**Comment by Bjwebb** [comment]
We've fixed the display disparity, but we're not happy with how it looks now, see https://github.com/OpenDataServices/grantnav/pull/267

One example that does display better is characters with accents. Compare:
http://current.acceptable-license-valid.iteration06.grantnav-dev.default.threesixtygiving.uk0.bigv.io/grant/360G-macc:RSI-S2
http://new.acceptable-license-valid.master.grantnav-dev.default.threesixtygiving.uk0.bigv.io/grant/360G-macc:RSI-S2

**Comment by KDuerden** [comment]
Thanks for this fix. It is an improvement but the heavy text seems to bleed a lot. Let me know if there is anything I can do.

**Comment by caprenter** [comment]
The real solution is to use a different font entirely.

This may or may not be a big issue for you. 

I understand our plans to make some tweaks this week, and that some design elements are part of that, we should be able to see what a different font would look like as part of that.

**Comment by kindly** [comment]
In #298 I have tried a different font called assistant.  I chose it out of https://fonts.google.com/ as:

- It looked vaguely similar (is a narrow font) to the existing font.
- Is openly licensed
- Has many font weights
- looks better (in my opinion) to how it looks currently

**Comment by robredpath** [comment]
I think there's potential here, for sure. The letters feel very widely spaced, now - I tried dropping letter-spacing to 0.5px and it looked much more natural. What do you think? 

@KDuerden, any thoughts? Screenshots:

![screen shot 2016-08-31 at 17 29 45](https://cloud.githubusercontent.com/assets/641009/18137536/95e7fc38-6fa0-11e6-86f9-71e382decd9c.png)
![screen shot 2016-08-31 at 17 29 25](https://cloud.githubusercontent.com/assets/641009/18137535/95e5e560-6fa0-11e6-85b2-83f1e15a6448.png)
