### ISSUE TITLE
Make 'new search' button more prominent

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/grantnav#291]
From steering committee:

	Look at making “new search” button more prominent – rename “start new search”? Or make the same size as the “clear all filters” button?

**Comment by robredpath** [comment]
I'll ask Shi to look at this

**Comment by notshi** [comment]
Demo - renamed to 'Clear all filters'

![screenshot_2016-08-31_17-18-52](https://cloud.githubusercontent.com/assets/1515961/18137204/506b0606-6f9f-11e6-9754-953c2b0bec77.png)

**Comment by robredpath** [comment]
I like the grey and the resized button. However, it can't be called 'clear all filters' as there's another button called that, which does something different:

![screen shot 2016-09-01 at 08 32 19](https://cloud.githubusercontent.com/assets/641009/18159014/a3c93802-701e-11e6-96b9-e7f22bec091e.png)

That button both clears all filters AND the search box. The 'clear all filters' button just removes any applied facets, and the magnifying glass lets you change the search term but keep all the facets you've applied.

**Comment by caprenter** [comment]
Sort of the idea for this is a kind of 'Start Over' option fro people - just clear everything, start a brand new search.

In some ways it's similar to going to the home page e.g. clicking the top left hand logo (but I don't think we want to do that as such).

I've always thought a link in the top (orange) nav bar/header area might work.

We've all struggled to come up with a good bit of text:
Start over
New Search
erm..

**Comment by notshi** [comment]
Ahh, I see. Wasn't sure what it meant to do! So it's like a 'Clear field' option so you don't have to hold down on the backspace.

**Comment by caprenter** [comment]
Not just that...

Start Over is really the best way I can describe it.

A user can:
type a search term, then apply filters, then remove some or all of those filters while retaining the search string.
If they want to they can keep the filters applied and search on a different term - this is handy if you are interested in grants over 10,000 in Bristol (first search 'children', second search 'football', etc)

Some times you just want to nuke all the filters, options, search terms and START AGAIN!

That;s the idea. Call me on a hangout if it's easier to talk through.

**Comment by notshi** [comment]
'Nuke all' seems good too.

Just reread the whole thing - it's basically starting a fresh search as if you've landed on the main page. I see why 'New Search' makes sense if you're going to use the tool extensively (then there's always 'recent / saved searches' history if you're going down that route). User feedback will be good.

**Comment by notshi** [comment]
Word tryouts - 

![start01](https://cloud.githubusercontent.com/assets/1515961/18168116/090f5ae8-704c-11e6-817a-c908aefd0446.png)

![start02](https://cloud.githubusercontent.com/assets/1515961/18168115/090d00a4-704c-11e6-8fb7-7ab7dd74d2ab.png)

**Comment by robredpath** [comment]
@caprenter is off today - can we call it Start Over, have our momentary cringe at the American-ness of it, and get this ready to merge?

**Comment by notshi** [comment]
Yup, sure. Am at an event right now but will be able to get this done by tonight.

**Comment by robredpath** [comment]
Amazing, thanks @notshi . I'm not going to get to reviewing it until at least the middle of Monday, so if you'd rather wait a little bit, that's fine!

**Comment by notshi** [comment]
No worries, submitted a pull request. Hopefully all is ok.
