### ISSUE TITLE
Underline on hover for big frontpage numbers looks odd

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/grantnav#297]
Hover:
![uploads/9e4beeb5-6c03-47bb-812f-d252d51c5fdc/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F9e4beeb5-6c03-47bb-812f-d252d51c5fdc%2Fblob)
No hover:
![uploads/f545a96c-37bd-42f3-ae43-d35457649935/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff545a96c-37bd-42f3-ae43-d35457649935%2Fblob)

**Comment by notshi** [comment]
This should be fixed with the new styling where there is no underline on hover.

**Comment by Bjwebb** [comment]
Yep, looks good.
