### ISSUE TITLE
Do we need Django 1.9?

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/grantnav#30]
I notice that gratnav is using Django 1.9, which is the latest, but Django 1.8 is LTS, which will be supported for longer. If we're not using any Django 1.9 specific features, then it might be good to downgrade to 1.8 for the longer support, and consistency with Cove.

**Comment by kindly** [comment]
I am happy either way. I was not aware of LTS release, so I would leave it up to you.

My logic for doing this was that if we track the latest releases then it will be easier to upgrade to later versions when they come out and not have such a large jump.

I think that we use very little non standard features that I do mind either way.

**Comment by Bjwebb** [comment]
Okay, I'm going to downgrade us to the 1.8 LTS.
