### ISSUE TITLE
Related Activity info is not in the Grants view

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/grantnav#309]
e.g. http://grantnav.threesixtygiving.org/grant/360G-wolfson-19928

should have related activity info (and identifier is given in the source data)

**Comment by caprenter** [comment]
the filed in standard says:
Related Activity 	The identifiers of any related activities (e.g. other grants given as part of a multi-grant project) 	array

**Comment by caprenter** [comment]
NB Related Activity Description is showing - I think this is being treated as an additional field and displayed as is. (It is not part of the standard, so this seems ok)

**Comment by stevieflow** [comment]
NB; the file http://www.wolfson.org.uk/media/2780/wolfson-foundation-grants-2014.xlsx seems to have two columns called ``Related Activity`` - will ask the publisher to correct this

AFAICS http://www.wolfson.org.uk/media/2814/wolfson-foundation-grants-2015.xlsx only has one ``Related Activity`` column though

**Comment by stevieflow** [comment]
@Bjwebb is ``Related Activity`` processed in the grant table?

**Comment by Bjwebb** [comment]
I suspect the problem is that no arrays of strings are shown correctly. @kindly probably knows better.
