### ISSUE TITLE
_x000D_ strings showing in parsed data

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/grantnav#311]
I'm guess that seeing _x000D_ in data is a result of the conversion from Excel, and I'm not sure if there is anything much that can be done.

I see it:
e.g. here: http://grantnav.threesixtygiving.org/grant/360G-wolfson-19925

**Comment by Bjwebb** [comment]
I don't think it's the conversion from excel. As far as I can tell `x000D` is actually in the spreadsheet text. I'm assuming it's an artefact of whatever system Wolfson has got the data out of originally, so needs fixing up at that stage (or cleaning up manually if it's a one off).

**Comment by robredpath** [comment]
I downloaded the original sheet from Wolfson's site and it looks like it's a newline in the original cell.

**Comment by stevieflow** [comment]
Possible - guidance in the standard repo about new lines

**Comment by morchickit** [comment]
Can I close this? Doesn't look like a GrantNav issue, but a standard  support issue. Can I move it there ?

**Comment by stevieflow** [comment]
Yes - to follow up with the publisher @morchickit

**Comment by morchickit** [comment]
Great, closing it here then!
