### ISSUE TITLE
Needs a Contributing document

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/grantnav#329]
We say at http://grantnav.threesixtygiving.org/developers :
Contributing to GrantNav

GrantNav is open source software developed by Open Data Services for 360Giving. We welcome feedback, comments and pull requests on GitHub. We hope that GrantNav provides a useful example of how to work with 360Giving data. If you're developing an application that uses 360Giving data, we'd love to hear from you - email us at info@threesixtygiving.org.

So we should have a contributing doc in place in this repo. We should be able to use the one from CoVE with minor edits

**Comment by robredpath** [comment]
This is done at https://github.com/OpenDataServices/grantnav/blob/master/CONTRIBUTING.md
