### ISSUE TITLE
Update requirements

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/grantnav#34]
There's various updates:
https://requires.io/github/OpenDataServices/grantnav/requirements/?branch=master

It might be worth looking into this approach, to make keeping these up to date (and not missing any new sub-dependencies!) easier.
https://news.ycombinator.com/item?id=11210370

**Comment by stevieflow** [comment]
This is tagged to Iteration 2.  Does it need to be?

**Comment by Bjwebb** [comment]
Nope, I just added it as I was planning to get it done then.

I ended up doing something similar for Cove, so it should be pretty quick to do the same thing again for GrantNav https://github.com/OpenDataServices/cove/pull/304

**Comment by Bjwebb** [comment]
Pull request https://github.com/OpenDataServices/grantnav/pull/65
