### ISSUE TITLE
Start over button often confused with search button

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/grantnav#352]
I have done this - and observed others too.  We can gather more evidence if needed

The "start over" button is often "hit" by people by mistake - thinking it is the search button.  We may want to revise the position/size of this button, relative to the search button

**Comment by KDuerden** [comment]
+1 to this!

**Comment by stevieflow** [comment]
I can see three things that can cause this behaviour:

1 - it's a button (click me!)
2 - it's directly next to the search bar (enter text here, then click me!)
3 - it contains an ambiguous term - Start Over *sounds* like it means search again, which could be interpreted as "search again, with the search terms I just input"
4 - the search icon - whilst it *is* a search icon - could be misinterpreted as being a graphical aspect of the search bar - there for decoration rather than function.

My proposal is to:

- remove the search icon from the search box (both on the homepage and elsewhere) 
- remove the Start Over button
- next to the search box have a button called "Search", which has the same function as the search icon button (but is outside of the search box)

This means we *lose* the functionality of the Start Over button - unless someone clicks on the homepage link (which is the "logo").  I would argue this is worth losing, as it is causing confusion currently, and a bad user experience

An alternative I can see is that we have an "x" in the search box (where the search icon is currently), for people to clear the text fields, but this might lead to further issues, potentially.

**Comment by Bjwebb** [comment]
I'm not convinced that we need to lose the current search button. I'd be happy to see "Start Over" go though.

**Comment by stevieflow** [comment]
> I'm not convinced that we need to lose the current search button. I'd be happy to see "Start Over" go though.

+1

**Comment by stevieflow** [comment]
The button is/was removed.  Ill close this in terms of the issue being resolved
