### ISSUE TITLE
Broken Link: Attributing GrantNav

### ISSUE THREAD

**Issue by ekoner** [OpenDataServices/grantnav#362]
This url: http://grantnav.threesixtygiving.org/datasets/attributing-grantnav  404's

![screenshot from 2017-01-02 13-25-35](https://cloud.githubusercontent.com/assets/4339603/21589975/4a9cdc02-d0ef-11e6-89e1-b3db2ead1e29.png)

**Comment by Bjwebb** [comment]
Looks like it's missing a hash http://grantnav.threesixtygiving.org/datasets/#attributing-grantnav

On 2 January 2017 13:28:53 GMT+00:00, Edafe Onerhime <notifications@github.com> wrote:
>This url:
>http://grantnav.threesixtygiving.org/datasets/attributing-grantnav 
>404's
>
>![screenshot from 2017-01-02
>13-25-35](https://cloud.githubusercontent.com/assets/4339603/21589975/4a9cdc02-d0ef-11e6-89e1-b3db2ead1e29.png)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenDataServices/grantnav/issues/362

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Bjwebb** [comment]
So, it's the link, rather than the page that's broken. The only link I'm aware of is on the datasets page, so I'll fix that, do flag if there's links elsewhere.

I've also run `linkchecker http://grantnav.threesixtygiving.org/ -r 2` and this link is the only one it finds that's broken.

**Comment by Bjwebb** [comment]
Pull request to fix this https://github.com/OpenDataServices/grantnav/pull/364

**Comment by Bjwebb** [comment]
This is fixed now on http://grantnav.threesixtygiving.org/datasets/
