### ISSUE TITLE
Searching for characters with accents

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/grantnav#381]
A search for  ``Esmée`` results in 2771 results (which may be expected) whereas ``Esmee`` returns five.

Are there any settings we can tweak in elastic to consider these two strings as the same?

**Comment by robredpath** [comment]
Given that GrantNav is targetted at a UK audience, we can probably just enable this: https://www.elastic.co/guide/en/elasticsearch/guide/current/asciifolding-token-filter.html

**Comment by Bjwebb** [comment]
Via @kindly: This may not be a simple config change: we may need to change every change individually, or do some work to make sure we also include the default English filters that we already use.

**Comment by Bjwebb** [comment]
@kindly was right, we do need to recreate the English analyzer, but luckily there's docs about exactly how to do that - https://www.elastic.co/guide/en/elasticsearch/reference/2.4/analysis-lang-analyzer.html#english-analyzer

**Comment by Bjwebb** [comment]
Dev instance to test: http://current.acceptable-license-valid.381-accents.grantnav-dev.default.threesixtygiving.uk0.bigv.io/
