### ISSUE TITLE
Exclude USD publisher(s)?

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/grantnav#388]
@morchickit @KDuerden - could an interim measure - in light of #379 & #387 - be to exclude Quixote Foundation from GrantNav loads?

**Comment by morchickit** [comment]
Interim means until we fix #387 ?

**Comment by stevieflow** [comment]
The GN load is the first if each month - so certainly 1st July (if we can)

**Comment by morchickit** [comment]
ok, let's do it, just waiting to @KDuerden to confirm

**Comment by KDuerden** [comment]
I'm not sold on this as a solution. 
Removing this file wouldn't fix the double counting issue which makes adding up the value problematic, and we don't currently have a way to exclude individual foreign currency grants within UK foundation data. We have a couple of Top 60 grantmakers preparing to publish who award in multiple currencies, and one of which operates in $ - although it isn't yet clear whether they will convert for the purposes of publishing. 
If putting the foreign currency amounts is to be discouraged, we should start making that clear in our publisher guidance.
This would change the premise of GrantNav as a mirror to and exploration tool for published/valid/open 360Giving data, but I realise that how this tool is understood and used is a key challenge, and that it will  evolve.

**Comment by stevieflow** [comment]
OK - so it's probably best to close this as a bad idea?

**Comment by robredpath** [comment]
Closing as this relates to particular files/data loads rather than GrantNav the software, and we've not acted on it for a couple of months.
