### ISSUE TITLE
Fix text on developers page

### ISSUE THREAD

**Issue by morchickit** [OpenDataServices/grantnav#394]
The whole data set is over 100MB and growing.. .
I just downloaded the new json file and it's way over 300MB (331MB to be exact). We need to signpost it (that it's now 331MB) better and explain how people can get slices of the data (basically by searching grantnav).

@stevieflow and @robredpath - we discussed about it last week, but now I actually downloaded the data, so can give better figures.

**Comment by morchickit** [comment]
Let me correct- the JSON is 331 MB, the CSV is 172MB. We just need to make sure people aware that the JSON is a monster

**Comment by stevieflow** [comment]
@morchickit thanks.  Please can you suggest the text change we need (which will be (nearly) futureproof):

Currently - this says: http://grantnav.threesixtygiving.org/developers

> The whole data set is over 100MB and growing, so we recommend that you store the data locally for your own application to work from.

**Comment by robredpath** [comment]
Current text: 

` The whole data set is over 100MB and growing, so we recommend that you store the data locally for your own application to work from. The data is updated at most once a day (except in case of an error), and usually once per week if there is new data available to load. A list of all data sets and the date on which they were last updated can be found at http://grantnav.threesixtygiving.org/datasets/#datasets-used`

How about this for new text, @stevieflow @morchickit ?

`The current data set is several hundred MB, and growing, so if you are using the data in an application we recommend that you download it and store it locally for your own application to work from. The data is updated at most once a day (except in case of an error), and usually once per month. A list of all data sets and the date on which they were last updated can be found at http://grantnav.threesixtygiving.org/datasets/#datasets-used

If you are downloading the whole data set for analysis, you may find that the size makes it very difficult or impossible to handle with desktop applications. We recommend that you carry out initial filtering or segmentation of the data with the GrantNav search interface and use the download links on the search results page to download the results in either JSON or CSV format. `

**Comment by stevieflow** [comment]
looks good

> The data is updated at most once a day

This might confuse - as we mainly update GrantNav once a month.  We're talking about GrantNav data here?

**Comment by robredpath** [comment]
@stevieflow hence why that sentence goes on to say "and usually once per month". Would "The data is typically updated once a month, and at most once a day ..." be clearer? The intention of that sentence is to discourage people from downloading the whole file more than once a day to check for changes.

**Comment by stevieflow** [comment]
@robredpath tbh, If we are talking about GN, then I'd just stick to the once a month story - as per: 

http://grantnav.threesixtygiving.org/datasets/

> We update GrantNav on a monthly basis.

Yes, it might get updated outside of this,, but best to leave out ambiguity imho

**Comment by robredpath** [comment]
@stevieflow I don't think there's any ambiguity here - we're specifying the frequency with which an application should check for updates (1 day) and the expected frequency of updates (1 month). If we push bad data, and it somehow goes live, we want to know that the correction will ripple through the ecosystem within a day rather than a month, surely? Also, if we specified monthly, as a user I'd want to know which day, which we can't specify with any accuracy. 

How about "The data is updated once a month, however if there is an error, it may be updated out-of-cycle to correct it. You should check for updates no more than once a day for new data". ?

**Comment by stevieflow** [comment]
@robredpath ok thanks - I can see what you mean now!

> How about "The data is updated once a month, however if there is an error, it may be updated out-of-cycle to correct it. You should check for updates no more than once a day for new data". ?

Yeah.  Although I'd just say:

> "The data is updated once a month, however if there is an error, it may be updated out-of-cycle to correct it.  

(and point to http://grantnav.threesixtygiving.org/take_down_policy)

**Comment by stevieflow** [comment]
> I think I'd rather be told how often I should check for new data.

AFAIK, we've had one month (the first!) when we had to change data mid-month.  Since then (nearly 16 months later), it's been a monthly update.  I just think it's easier to stick to that line.

As for the *specific* day when that happens, then it could be useful to have a service to get that as a notice....

**Comment by Bjwebb** [comment]
> Alternatively, is this a good time to create a simple service to get the last updated time, which we should tell people to check before downloading? @Bjwebb @kindly ?

Yes, I think that could be useful.

I think what people want to know is when we make the "flip" to live, so a simple first iteration of this could be a file in `static` that we pipe a `date` command into when doing the flip.

**Comment by robredpath** [comment]
> I think what people want to know is when we make the "flip" to live

As a developer who runs an application that depends on GrantNav data, I want to know when new data is available so that I don't waste effort downloading old data but I still remain up-to-date

So, a file I can check regularly for an updated time would be perfect

**Comment by stevieflow** [comment]
> So, a file I can check regularly for an updated time would be perfect

Should that now be a new issue?  And we maintain the fix on the text here (which would be best to do when the alert is in place?)?

**Comment by robredpath** [comment]
@stevieflow - https://github.com/OpenDataServices/grantnav/issues/444 is the new issue. 

In the short-term, we should at least update the text relating to the volume of the data file.

**Comment by stevieflow** [comment]
@robredpath yes please

**Comment by morchickit** [comment]
Ok, text looks good to me (I think that for now, saying that GrantNav is updated once a month is fine). We might want to add that for any question or feedback on the data they can post on the forum -https://forum.threesixtygiving.org/c/grantnav or email - grantnav@threesixtygiving.org

**Comment by robredpath** [comment]
Thanks @morchickit . There is always a link to the email address and the Help with Using GrantNav page in the footer, so I don't think we need to add it to the text on this page as well.

**Comment by morchickit** [comment]
Yeah, but people sometimes ignore the footer. The page is short though, so you are probably right.

**Comment by robredpath** [comment]
The new text is live
