### ISSUE TITLE
Signposting - what does £0 mean on GrantNav

### ISSUE THREAD

**Issue by morchickit** [OpenDataServices/grantnav#410]
So, £0 doesn't always mean that the grant wasn't given, sometimes it is for salaries, sometimes it is because of regranting. Either way, we need to tell users to look at the publisher's guidelines to understand what 0 is.

**Comment by stevieflow** [comment]
Therefore, is the proposal for some kind of generic statement / alert text when the grant value = 0?

**Comment by morchickit** [comment]
I don't know how to implement this signposting. I thought of a tooltip in
the facets. I just a added this as part of our next signposting iteration.

**Comment by robredpath** [comment]
I think this would work - with the (i) being linked to a 'Why are there £0 grants?' question on the Help page

![Screen Shot 2018-09-06 at 17.01.15.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57da8df3e209c5130041c438/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6454f56b7191a379e80c2b50415e4bbe5d4a1f06a3a3dc78e2a436628f555feed66f5972933519fab0861fbf03bf76884e82e4ef9850d2aa6c7bb3d4d216744b470a83ed5f35aa984ecb5ef44fe84b5da2143064f43b.png)

**Comment by morchickit** [comment]
Yes! Sounds like a plan!

**Comment by robredpath** [comment]
This is now live
