### ISSUE TITLE
Some fields in the grants sheet are missing from the CSV download

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/grantnav#449]

**Comment by robredpath** [comment]
Amount Applied For

**Comment by BobHarper1** [comment]
- Amount Disbursed
- Any of the planned dates apart from `Planned Dates:Duration (months)`
- All of the actual dates fields
- Funding/recipient organisation addresses (do we want to include all the `organization` object fields in export? Maybe postal codes would be useful though i.e. `recipientOrganization.0.postalCode` `fundingOrganization.0.postalCode`).
- From Open Call?

There would still be more (e.g. `Transaction` and `Classification` fields) but it maybe then becomes a question of what is useful to export? Including everything that the standard covers could grow the number of fields to hundreds.

**Comment by morchickit** [comment]
I am not convinced it all need to be in the GrantNav CSV download.

**Comment by BobHarper1** [comment]
N.B. These are all the Standard fields that GN does export to https://github.com/OpenDataServices/grantnav/blob/master/grantnav/csv_layout.py

**Comment by robredpath** [comment]
The fields mentioned above are now in the download. Others can be added on request. Agreed that we don't want to try and get universal coverage.
