### ISSUE TITLE
GrantNav show no results in table pages

### ISSUE THREAD

**Issue by morchickit** [OpenDataServices/grantnav#452]
See funder table example - http://grantnav.threesixtygiving.org/funder/GB-COH-IP00525R
Or recipients - http://grantnav.threesixtygiving.org/recipients

It was ok yesterday, so maybe something with recent pull requests?

**Comment by BobHarper1** [comment]
I noticed the same but see it's working as expected now. Possibly a result of restarting the server after the latest update with the additional csv fields thing.

**Comment by morchickit** [comment]
Ok, closing it now, since all is normal.
