### ISSUE TITLE
Fuzzy search is not working 

### ISSUE THREAD

**Issue by morchickit** [OpenDataServices/grantnav#453]
Only work at the end of a word, ie work on gir~ but not on wom~n

**Comment by morchickit** [comment]
@robredpath - worth documenting this in our sprint now.

**Comment by robredpath** [comment]
@morchickit the advanced search page only gives examples with the ~ at the end of the word, which is the correct way to use the fuzzy operator. Replacing missing characters is the function of wildcards, which are documented in the section above. 

I've switched this to being a documentation issue.

**Comment by robredpath** [comment]
We've clarified use of the fuzzy search operator in the docs
