### ISSUE TITLE
Grantee page - default ordering

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/grantnav#46]
Im not sure what the default ordering for a grantee page is.  I had expected it to be by date (descending) , but it doesnt appear to be: recipient/GB-COH-5303626

![dates](https://cloud.githubusercontent.com/assets/1209944/13611971/0c88515e-e55d-11e5-821d-f4fccccdd90c.png)

**Comment by stevieflow** [comment]
I noticed on this page that the "key facts" for earliest and latest award date, is blank... is this a data issue rather than Grant Nav?

**Comment by kindly** [comment]
Yes that is a data issue, all the dates with that funder just contain the are like 09/2015.  The frontend tries its best to display them in the best way it can but the search engine is very unhappy does not recognise them as dates and does not allow stats or sorting. Not sure there is much we can do apart from sort out the data.
