### ISSUE TITLE
ward codes incorrect

### ISSUE THREAD

**Issue by drkane** [OpenDataServices/grantnav#464]
Haven't looked at why - but it looks like some of the values in "Recipient Ward Geographic Code" are incorrect. It seems to be that they are based on a lookup to the ward name rather than the code, which causes issue where wards have duplicate names.

For example, grants that should have been in ward `E05000400` - Alexandra Ward in Kingston Upon Thames were instead assigned to `E05000719` - Alexandra Ward in Oldham.

**Comment by drkane** [comment]
Looking into it a bit further, I think [/dataload/import_to_elasticsearch.py#L388-L399](https://github.com/OpenDataServices/grantnav/blob/master/dataload/import_to_elasticsearch.py#L388-L399) is part of the problem here. 

I think adding `ward_code` to the `postcode_to_area` dict, and adding a check for `ward_code` to the `add_area_to_grant()` function ([#L285](https://github.com/OpenDataServices/grantnav/blob/master/dataload/import_to_elasticsearch.py#L285)) would probably do the trick.

**Comment by Bjwebb** [comment]
Yes, I think that would work. @kindly Could you double check?

**Comment by morchickit** [comment]
@robredpath - Can we close this?
