### ISSUE TITLE
API: Set content-length header

### ISSUE THREAD

**Issue by andylolz** [OpenDataServices/grantnav#474]
For [/api/grants.json](http://grantnav.threesixtygiving.org/api/grants.json) and [/api/grants.csv](http://grantnav.threesixtygiving.org/api/grants.csv), the content-length header isn’t set. This is problematic for people (like me!) on a slow and unreliable connection. A download progress bar is super useful.

**Comment by Bjwebb** [comment]
These are streamed, so its difficult to know ahead of time how large the file will be.

**Comment by andylolz** [comment]
Yeah, [I see](https://github.com/OpenDataServices/grantnav/blob/1d66fc393e0a849519e2eba940a113c89be29aa4/grantnav/frontend/views.py#L106-L131).

Could maybe count rows and approximate?

**Comment by andylolz** [comment]
Okay, not a big issue. Closing.
