### ISSUE TITLE
When searching on GrantNav free search, do not search on file name

### ISSUE THREAD

**Issue by morchickit** [OpenDataServices/grantnav#479]
Searching on the phrase "open data" leads to 800 grants, but that's because of the filename of Tudor and Southwark which has the phrase "open data" in them. I am not sure most users understand that it brings lots of false positives.

**Comment by robredpath** [comment]
Suggestion: Add 'Search titles & descriptions' to dropdown on front page, and make it default

**Comment by robredpath** [comment]
If elastic does support reporting which fields the result was found in, display that

**Comment by BibianaC** [comment]
@morchickit @robredpath is it ok to close this issue?
