### ISSUE TITLE
Title & Descriptions search option gives no results

### ISSUE THREAD

**Issue by KDuerden** [OpenDataServices/grantnav#489]
I see the new search options are live. Unfortunately I am getting no results at all for any searches. Can you check if this function working as intended or not @BibianaC

**Comment by BibianaC** [comment]
@KDuerden I'm going to have a look.

**Comment by BibianaC** [comment]
@KDuerden now is working.

**Comment by KDuerden** [comment]
@BibianaC  thank you!

**Comment by KDuerden** [comment]
Related to this - all grant records in GrantNav now have a combine title_description field showing:
Eg: http://grantnav.threesixtygiving.org/grant/360G-blf-A4E_2_010104613
Is it a bug that it is visible here?
