### ISSUE TITLE
Unclear what organisationType field in JSON standard should look like

### ISSUE THREAD

**Issue by mattandrews** [OpenDataServices/grantnav#490]
On the latest [standard](http://standard.threesixtygiving.org/en/latest/_static/docson/index.html#../360-giving-schema.json) document for `fundingOrganization.organisationType`, the guide looks like this:

![image](https://user-images.githubusercontent.com/394376/45689818-c9a8ed80-bb4c-11e8-9c6d-7bd49a8a8183.png)

This looks a bit broken – I'm not clear what options we have for fields here.

I'm attempting to format strings like `School : Voluntary Controlled School` into the Grantnav standard but struggling a bit here to work out how to represent this. Ideally we'd break apart that string (eg. into `School` as a top-level organisation type, and `Voluntary Controlled School` as a sub-type) but it's not clear what your standard suggests – any tips?

**Comment by morchickit** [comment]
This is connected to this issue in the standard. https://github.com/ThreeSixtyGiving/standard/issues/255
We are working on it!

**Comment by mattandrews** [comment]
Thanks!
