### ISSUE TITLE
st marys and st mary's

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/grantnav#54]
These two search terms produce the same results.  Is this something we have configured?

**Comment by kindly** [comment]
This is something that the search index does automatically, not sure we should fix it as its useful in most cases.

**Comment by stevieflow** [comment]
Thanks @kindly 

Have shifted to backlog, as dont think there is any action at all / right now - but maybe one to revisit

**Comment by stevieflow** [comment]
Closing - this isnt relevant right now
