### ISSUE TITLE
Footer - build ID / github links etc

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/grantnav#55]
As per CoVE, we could / should insert a footer on GrantNav to detail relevant info links around the code repository and build ID etc.  

This can be themed later, but wanted to post as a specific task

**Comment by robredpath** [comment]
@stevieflow and Katherine at 360 are designing a new footer for GN, so it's worth discussing this with them before proceeding

**Comment by robredpath** [comment]
Can this be an abbreviated sitemap, like a lot of modern pages do?

**Comment by Bjwebb** [comment]
AFAIK this issue is about having a "Running version cf9e7a9" like cove does http://cove.opendataservices.coop/ in the footer.

**Comment by stevieflow** [comment]
I think I can create a new ticket to change the footer text - but this issue was about the build ID , as per the above suggestion from @Bjwebb https://github.com/OpenDataServices/grantnav/issues/55#issuecomment-239789348

In relation to this, would we want to also include the dateTime of the deployment - as I understand we teh version we are running could be stable, but the deployments differ..

( @Bjwebb a bit like the dateTime stamp on the IATI dashboard footer)

**Comment by Bjwebb** [comment]
I don't think there is a clearly defined point at which "deployment" happens. AFAICT the useful information is the commit the code is on, and the datetime that the data was downloaded.

**Comment by stevieflow** [comment]
>  datetime that the data was downloaded.

... which is actually in the provenance page /datasets/ , which will be a link in the footer

**Comment by robredpath** [comment]
Note from going live doc: ">> Directing software feedback - via GitHub would be suffice. We expect that those who are “in the know” will be able to locate (via footer link) and use this"
