### ISSUE TITLE
Data Licencing information

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/grantnav#59]
We should be publishing information in relation to the licence of data used, and in terms of any re-use of the data as presented by GrantNav

**Comment by stevieflow** [comment]
Would you see that being published alongside #60 , and/or being more accessible / obviously associated with each grant (page)>?

**Comment by caprenter** [comment]
We should be doing the best we can with this.

A minimum would be a simple statement somewhere (remember that re-use is also part of this ask)
A best effort depends on context - think of a list off 100 search results from many orgs (that someone wishes to use), or an aggregate figure, or a single grant - each would need a different approach I suspect.

**Comment by Bjwebb** [comment]
I think we have this covered with our new datasets page as part of https://github.com/OpenDataServices/grantnav/issues/166
