### ISSUE TITLE
Terms and conditions

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/grantnav#61]
GrantNav needs a terms and conditions of use page

**Comment by caprenter** [comment]
There is a pull request in for this

**Comment by caprenter** [comment]
I'm going to also add a link in the footer to a page about a Take Down policy. The page will direct people to the statement on the 360Giving main website: http://www.threesixtygiving.org/take-down-policy/

**Comment by caprenter** [comment]
Task is to read the t&cs

**Comment by robredpath** [comment]
Looks good - I think it's a fair policy that's fit for purpose with the data and setup that we currently have. I think it's important that the community feel able to respond to the policy (although ideally not in the context of a takedown request in progress!), so we do welcome feedback.
