### ISSUE TITLE
Cookie Policy

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/grantnav#62]
GrantNav needs a policy about user privacy and should incorporate the EU Cookie directive requirements

**Comment by Bjwebb** [comment]
GrantNav doesn't currently use any cookies, but this is likely to change with https://github.com/OpenDataServices/grantnav/issues/21

**Comment by robredpath** [comment]
Made a note about cookies on #21 . +1 to a privacy policy as part of going live

**Comment by robredpath** [comment]
Turns out we already have cookies. We should add cookie control!

**Comment by caprenter** [comment]
I'm not sure why this is assigned to me.

I'll rename this to Cookie policy, create a new Privacy policy issue to separate them out.

This could be a solution: https://pypi.python.org/pypi/django-cookie-law/1.0.1
but I don't think I'm the person to implement it.

**Comment by caprenter** [comment]
I've implemented and there is a pull request: https://github.com/OpenDataServices/grantnav/pull/176
