### ISSUE TITLE
Footer navigation

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/grantnav#67]
Block that lists pages to navigate to:

- About
- Help
- Contact
- Data sources

**Comment by caprenter** [comment]
GrantNav footer


360Giving logo (non-bagpipe version)

360Giving provide support for grantmakers to publish their grants data openly, to understand their data, and to use the data to create online tools that make grantmaking more effective.

Find out more about 360Giving
GrantNav uses open data published to the 360Giving standard.  

GrantNav enables people to search, filter and download across these datasets, for free.

Got some feedback?  Visit here or send emails to grantnav@threesixtygiving.org
Links

Funders
Recipients


Terms and Conditions
Take Down Policy
Data used in GrantNav
Reusing GrantNav data
Copyright


Code / Github
Release / deployment details?

**Comment by caprenter** [comment]
waiting on @Bjwebb to do https://github.com/OpenDataServices/grantnav/issues/55
