### ISSUE TITLE
Page for Region | Page for District

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/grantnav#71]
As per page for Funding Org, a click-thr page that details

- Stats summary
- Recipient Orgs 
- Grants

This will be an expectation from the location facet I think - "can I see a page with all grants in Fulchester?"

**Comment by kindly** [comment]
This is not actually very trivial as will require some thinking as to what goes on these pages.
i.e what stats we want to show and do we want a table for recipeints and funderst.

Put it in the backlog for now.

**Comment by stevieflow** [comment]
My suggestion is to follow the /funder page for region/district.  

The reason I cite that rather than /recipient is that the table to pull grantees together could be useful by region/district

**Comment by kindly** [comment]
It may also be interesting to have a table of funders as we do grantees for this page i.e what funders give to each region/district.

Also there is a case for on each funder page having a table of regions/district where the funder gives.

**Comment by stevieflow** [comment]
Yes, agree - can see what you mean @kindly 

We also discussed the clickthru to region/district being on the search results and grant page, so can agree that this starts to increase in workload/considerations

**Comment by kindly** [comment]
This is partially done in a84f57d.  Needs some more discussion as to what should be on these pages

**Comment by robredpath** [comment]
Closing as there's a more nuanced location conversation that's starting to get captured
