### ISSUE TITLE
What facets do I have "on"?

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/grantnav#78]
As a user, it might be useful to provide some feedback to me at the top of the search results in terms of what facets I have "switched on" 

I have observed people freetext search and not realised that facet choices are carried over.  Hence, some print out if what facets are active* may help

* there's a UI problem looming here, in terms of many many facets being selected at once

**Comment by caprenter** [comment]
"I have observed people" == 1 person?

**Comment by stevieflow** [comment]
@caprenter true, although I also had that thought too

**Comment by robredpath** [comment]
This is fundamentally the 'facets are retained when doing a new search' issue which is addressed in #132
