### ISSUE TITLE
Reload data without downtime

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/grantnav#83]
We could use https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html for this.

**Comment by robredpath** [comment]
@Bjwebb is this dealt with by blue/green?

**Comment by Bjwebb** [comment]
Partly. This also relates to the multiple installations we want with different data/code https://github.com/OpenDataServices/grantnav/issues/273
