### ISSUE TITLE
Create page for Help

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/grantnav#9]
We can start with the content we have written, and refine / test

**Comment by caprenter** [comment]
The Elasticsearch backend provides very powerful search capabilities, and we can use those features to help us with some of our use cases (e.g. to search just a single publisher, or a group of publishers data.)

See below for a 'dummies' guide to search based on the ElasticSearch docs 

Search for:

Words and phrases:
a single word: e.g. people
all words: e.g. young people gardens
require each word to be found: e.g. young AND people
an exact phrase by enclosing it in quotes. e.g. "young people"

Using the above you can effectively filter the records to a e.g. a single publisher. Try:
"The Dulverton Trust"

Fields:
a specific field. e.g. title:gardens (will search the "title" field for the word "gardens") 
a field with no value (or is missing): e.g.  _missing_:description (search the field "description" for grants that have no value (or is missing))
a field that has any non-null value: e.g. _exists_:title

Fields are shown on many records. Others you might like to try:
title
description
and see the list of field names via the stats:
http://grantnav.grantnav-dev.default.opendataservices.uk0.bigv.io/stats

Ranges
Dates:
Find grants in a date range
Planned start date in 2012:  plannedDates.startDate:[2012-01-01 TO 2012-12-31]
Planned start date in 2012 and planned end date in 2014: plannedDates.startDate:[2012-01-01 TO 2012-12-31] AND plannedDates.endDate:[2014-01-01 TO 2014-12-31]

Amounts:
Amount awarded between £0 and £100: amountAwarded:[0 TO 100]
Amount awarded between £500 and £1000: amountAwarded:[500 TO 1000]

You can also do some ranges with one side unbounded:
amountAwarded:>1000
amountAwarded:>=1000
amountAwarded::<1000
amountAwarded:<=1000

You can also use the * wildcard (see below) when asking for a range. e.g. amountAwarded:[500 TO *]

Wildcards
Wildcard searches can be run on individual terms, using ? to replace a single character, and * to replace zero or more characters: e.g. b?g, you*qu?ck bro*

Fuzziness
We can search for terms that are similar to, but not exactly like our search terms, using the “fuzzy” operator: e.g. youht~ yung~ pple~quikc~ brwn~ foks~


For more examples and functionality see:
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-string-syntax

**Comment by stevieflow** [comment]
@caprenter is the above text a start of what would be a help page?

@kindly would a page like this be written in markdown or similar?  Would it be within this repo?

**Comment by caprenter** [comment]
the text above is the text we created in a goggle doc - what I assume you refer to as 'content we have written,'

**Comment by stevieflow** [comment]
@caprenter yep

**Comment by robredpath** [comment]
Let's create a page, call it 'advanced search', link to it from the front page but make sure that we don't do this at the expense of really good contextual help text on the front page
