### ISSUE TITLE
Organizations (facets)

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/grantnav#95]
We have a label with US English 

``Organizations`` (Recipient and Funding)

I think this is how the standard (see https://github.com/ThreeSixtyGiving/standard/issues/104) - but in Grant Nav can we use ``Organisations`` instead?

**Comment by robredpath** [comment]
Although -ize is more commonly used in the US and -ise in the UK, both are valid in British English - see http://blog.oxforddictionaries.com/2011/03/ize-or-ise/ 

I think this wouldn't be trivial as I suspect that GrantNav pulls those headings from the standard. 

Closing for now, if we get feedback that this is an issue we can re-open it and address it alongside any other minor UI tweaks
